### ISSUE TITLE
Application not starting on new KDE Slimbook

### ISSUE THREAD

**Issue by DrAxelbauer** [Slimbook-Team/slimbookintelcontroller#31]
Hi there!
I just tried to install and run the slimbookintelcontroller but it is not starting.

Here is thee output:
`benji@Benjis-Slimbook:~$ slimbookintelcontroller
A
/usr/share/slimbookintelcontroller/src
Cannot open log file /var/slimbookintelcontroller.log, using /tmp/slimbookintelcontroller.log
Gurrent path: /usr/share/slimbookintelcontroller/src
Cpu not found
Traceback (most recent call last):
  File "/usr/bin/slimbookintelcontroller", line 34, in <module>
    import slimbookintelcontroller
  File "/usr/share/slimbookintelcontroller/src/slimbookintelcontroller.py", line 71, in <module>
    cpu, model_cpu, version, number, line_suffix = (
TypeError: cannot unpack non-iterable NoneType object
`
Any hints how to get it running proberly?

Operating System: KDE neon 5.27
KDE Plasma Version: 5.27.8
KDE Frameworks Version: 5.110.0
Qt Version: 5.15.10
Kernel Version: 5.15.0-84-generic (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 5700U with Radeon Graphics
Memory: 30.7 GiB of RAM
Graphics Processor: AMD Radeon Graphics
Manufacturer: SLIMBOOK
Product Name: PROX-AMD5

**Comment by DrAxelbauer** [comment]
sorry but i have a amd cpu 🙈
